export const GET_ALL_MOVIES = "GET_ALL_MOVIES";

export const GET_ALL_SERIES = "GET_ALL_SERIES";

export const GET_SEASONS_BY_SERIES_ID = "GET_SEASONS_BY_SERIES_ID";

export const GET_ALL_GENRES = "GET_ALL_GENRES";

export const GET_ALL_PLANS = "GET_ALL_PLANS";

export const GET_WATCH_LATER_BY_CUSTOMERID = "GET_WATCH_LATER_BY_CUSTOMERID";

export const GET_WATCH_HISTORY_BY_CUSTOMERID = "GET_WATCH_HISTORY_BY_CUSTOMERID";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";

export const GET_REVIEWS_BY_MOVIES_ID = "GET_REVIEWS_BY_MOVIES_ID";
export const ADD_REVIEW = "ADD_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";

export const SIGNUP = "SIGNUP";
export const LOGIN = "LOGIN";